/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staff;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import Koneksi.koneksi;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author hp
 */
public class databukustaff extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public String kdbuku, jdlbuku, kategori;
    /**
     * Creates new form formbukustaff
     */
    public databukustaff() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }
    
     protected void aktif(){
        txtcaribukustaff.requestFocus();
    }

     protected void kosong(){
        txtcaribukustaff.setText("");
    }
     public void cetak() {
      try{
           String path="./src/laporan/lapbuku.jasper";
           HashMap parameter = new HashMap();
           JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
           JasperViewer.viewReport(print,false);
       }catch(Exception ex){
           JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada"+ex);
       }
}
     protected void datatable(){
      Object[] Baris = {"Kode Buku", "Judul", "Kategori", "Pengarang", "Penerbit", "Stok", "Tahun", "Halaman", "Deskripsi"};
    tabmode = new DefaultTableModel(null, Baris);
    String cariitem = txtcaribukustaff.getText();

    try {
        String sql = "SELECT * FROM buku WHERE kode_buku LIKE '%" + cariitem + "%' OR judul_buku LIKE '%" + cariitem + "%' ORDER BY kode_buku";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString("kode_buku"),
                hasil.getString("judul_buku"),
                hasil.getString("kategori"),
                hasil.getString("pengarang"),
                hasil.getString("penerbit"),
                hasil.getInt("stok"),
                hasil.getString("tahun_terbit"),
                hasil.getInt("halaman"),
                hasil.getString("deskripsi")
            });
        }
        tblbukustaff.setModel(tabmode);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e);
    }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbukustaff = new javax.swing.JTable();
        txtcaribukustaff = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bkembali = new javax.swing.JButton();
        bpinjam = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Buku"));

        tblbukustaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbukustaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbukustaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbukustaff);

        txtcaribukustaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcaribukustaffKeyPressed(evt);
            }
        });

        bcari.setBackground(new java.awt.Color(51, 102, 255));
        bcari.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bcari.setForeground(new java.awt.Color(0, 0, 0));
        bcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/researc.png"))); // NOI18N
        bcari.setText("CARI");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Kata Kunci :");

        bkembali.setBackground(new java.awt.Color(255, 153, 51));
        bkembali.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bkembali.setForeground(new java.awt.Color(0, 0, 0));
        bkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow.png"))); // NOI18N
        bkembali.setText("BACK");
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });

        bpinjam.setBackground(new java.awt.Color(102, 255, 102));
        bpinjam.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        bpinjam.setForeground(new java.awt.Color(0, 0, 0));
        bpinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book.png"))); // NOI18N
        bpinjam.setText("PINJAM");
        bpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpinjamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcaribukustaff, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bcari)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bpinjam)
                        .addGap(18, 18, 18)
                        .addComponent(bkembali)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcaribukustaff, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpinjam)
                    .addComponent(bkembali)))
        );

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null)));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("DATA BUKU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel6)
                .addGap(284, 284, 284))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        new dashboardstaff().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_bkembaliActionPerformed

    private void bpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpinjamActionPerformed
         // Cek apakah baris sudah diklik
    if (kdbuku == null || jdlbuku == null || kategori == null) {
        JOptionPane.showMessageDialog(null, "Pilih buku terlebih dahulu!");
        return;
    }

    // Kirim data buku ke formpeminjamanstaff
    formpeminjamanstaff f = new formpeminjamanstaff();
    f.kdbuku = this.kdbuku;
    f.jdlbuku = this.jdlbuku;
    f.kategori = this.kategori;
    f.itemTerpilih(); // set data di form peminjaman

    f.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_bpinjamActionPerformed

    private void txtcaribukustaffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaribukustaffKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datatable();
        }
    }//GEN-LAST:event_txtcaribukustaffKeyPressed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
       datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void tblbukustaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbukustaffMouseClicked
         int bar = tblbukustaff.getSelectedRow();
    String kode = tabmode.getValueAt(bar, 0).toString();
    String judul = tabmode.getValueAt(bar, 1).toString();
    String kategori = tabmode.getValueAt(bar, 2).toString();

    // Simpan ke variabel global
    this.kdbuku = kode;
    this.jdlbuku = judul;
    this.kategori = kategori;
    }//GEN-LAST:event_tblbukustaffMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(databukustaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(databukustaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(databukustaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(databukustaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new databukustaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bkembali;
    private javax.swing.JButton bpinjam;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbukustaff;
    private javax.swing.JTextField txtcaribukustaff;
    // End of variables declaration//GEN-END:variables
}
